@startuml Design Class Diagram for models

namespace Rally.Models {
    class User {
        + Tracks: ICollection<Track>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    }

    class Track {
        + Id: int
        + Name: string
        + Comment: string
        + Location: string
        + Date: DateTime
        + User: User
        + Category: Category
        + Signs: ICollection<Sign>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    }

    class Sign {
        + Id: int
        + SignNumber: int
        + XCoordinate: string
        + YCoordinate: string
        + Rotation: string
        + Exercise: Exercise
        + Track: Track
        + Equipment: Equipment
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    }

    class Equipment {
        + Id: int
        + XCoordinate: string
        + YCoordinate: string
        + Rotation: string
        + EquipmentBase: EquipmentBase
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    }

    class EquipmentBase {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        + Id: int
        + Image: string
        + Exercises: ICollection<Exercise>
        + Equipment: ICollection<Equipment>
    }

    class Exercise {
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    + Id: int
    + Description: string
    + Image: string
    + EquipmentBase: EquipmentBase
    + Category: Category
    }

    class Category {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        + Id: int
        + Name: string
        + Rules: string
        + Tracks: ICollection<Track>
        + Exercises: ICollection<Exercise>
    }

    User "1" -- "0..*" Track
    Track "0..*" -- "1" Category
    Track "1" -- "0..*" Sign
    Sign "0..*" -- "1" Exercise
    Sign "1" -- "1" Equipment
    Equipment "1" -- "0..*" EquipmentBase
    Exercise "0..*" -- "1" EquipmentBase
    Category "1" -- "0..*" Exercise

}



@enduml
